# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca3b4481b6a36c21a7f2e08c1c6afb72fe23f509f417cc7cfbdbb84e5285002d16948ee01994064dbd97ae9517f2b391519371b56d531e1efd7284d092ee9f22

test:
  secret_key_base: 3a7be2090a55122380bb725d82ef45acb6c481664e314f5e2ff7a26d97ec5ddc175ed06141c9e860650c9b61c3cfcb65b33af5420b7218eeafd2fe10a789bb6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
